### ISSUE TITLE
Trying to test microservices using elastest

### ISSUE THREAD

**Issue by GMMULLER** [elastest/elastest#25]
I'm Vânia's student at UFF and i started to study how to use elastest with microservices and some problems appeared:

I'm trying to test a microservice that is a simple CRUD, and reading the documentation i figured out that i had to use a SuT for the microservice and a TJob for the test file. 

SuT's config:

![Captura de tela de 2019-06-21 16-15-38](https://user-images.githubusercontent.com/39245943/59946143-1903ad80-9440-11e9-86c2-4611066004a5.png)
 
I used the image elastest/test-etm-alpinegitjava as container image because it has git and, apparently, docker.

In the docker-compose file i'm mapping the web container port 5000 to host's 5000 port, and in the SuT config i also put the port as 5000.

TJob config:

![Captura de tela de 2019-06-21 16-06-07](https://user-images.githubusercontent.com/39245943/59946319-992a1300-9440-11e9-95f8-96ae078a2801.png)

This time i used the epcallan/php7-testing-phpunit:7.1-phpunit5 image to have access to git and phpunit.

The file i'm running with phpunit just make a get request to my API.

![Captura de tela de 2019-06-21 16-35-05](https://user-images.githubusercontent.com/39245943/59947082-b3fd8700-9442-11e9-9bd3-17bdf80e0e5f.png)

When i run the TJob it works but apparently the SuT container doesn't start because it can't cd into a specific repository and the "ET_SUT_HOST" environment variable stays NULL. Besides that it takes so long to to execute everything. I don't if this is the right aproach to work with microservices in elastest.

The log report:

![Captura de tela de 2019-06-21 16-54-07(1)](https://user-images.githubusercontent.com/39245943/59948372-3b98c500-9446-11e9-91c1-da8e9503f1f2.png)

- Command executed to start ElasTest
docker run --rm -v ~/.elastest:/data -v /var/run/docker.sock:/var/run/docker.sock elastest/platform start
- I'm running on a **local machine**.

**Comment by EduJGURJC** [comment]
Hi @GMMULLER.

The `elastest/test-etm-alpinegitjava` image a does not contain docker, but you can use `elastest/test-etm-alpinedockerjava` image, as indicated in the description below:
![image](https://user-images.githubusercontent.com/26252085/59961885-967dfb00-94de-11e9-9a0c-619df53a6715.png)

On the other hand, elastest does not allow binding of ports in the docker-compose.yml, as there can be conflicts if more than one execution is launched at the same time. Just use `expose`, and in the test you will have access to the `ET_SUT_HOST` variable which will contain the internal IP of the container.

If you don't want to modify your docker-compose in GitHub, you can use the SuT option "With Docker Compose", paste the code of your docker-compose.yml and modify ports by expose:

```
version: '3'

services:
  sac-api:
    build:
      context: .
      dockerfile: dockerFiles/web.dockerfile

    expose:
        - 5000
    
    volumes:
      - ./src:/var/www/html
    
    depends_on:
      - sac-db
  
    environment:
      - ConnectionString=Server=sac-db;Port=3306;Database=sac_web_api;Uid=sac_web_api_ufjf;Pwd=s@cw3b4p1;
  sac-db:
    image: mysql:5.7

    volumes:
      - ./database:/var/lib/mysql
      - ./db-import.sql:/docker-entrypoint-initdb.d/dump.sql
    
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sac_web_api
      MYSQL_USER: sac_web_api_ufjf
      MYSQL_PASSWORD: s@cw3b4p1
```

![image](https://user-images.githubusercontent.com/26252085/59961975-66832780-94df-11e9-9908-ed4da8ead0a5.png)

I hope it's been helpful to you.
